apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-cfg
data:
  jupyterhub_config.py: ""

  jupyterhub_admins: "admin"
  gpu_mode: ""
  singleuser_pvc_size: 20Gi
  notebook_destination: <notebook_destination>
  culler_timeout: "31536000" # 1 year in seconds
